#!/usr/bin/env bash
# Install nginx web server and redirect.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "30i location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n" /etc/nginx/sites-available/default
sed -i "30i location /xwz {\nreturn 404 \"Ceci n'est pas une page\n\n\";\n}\n" /etc/nginx/sites-available/default
service nginx restart
