#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sed -i "30i location /xwz {\nreturn 404 \"Ceci n'est pas une page\n\n\";\n}\n" /etc/nginx/sites-available/default
service nginx restart
