#!/usr/bin/env bash
# Install nginx web server and redirect and more
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

config_path="/etc/nginx/sites-available/default"

sed -i "30i location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n" $config_path
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' $config_path
sudo sed -i 's/=404/@404/g' $config_path

# Add a custom header to the main location block
sudo sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By '$(hostname)';/" $config_path
sudo service nginx restart
