#!/usr/bin/env bash
# Install nginx web server and redirect and more
udo apt-get update -y
sudo apt-get install nginx -y
sudo sed -r -i "/^\s+server_name .+;/a\ \\tadd_header X-Served-By \$HOSTNAME\;\n" /etc/nginx/sites-available/default
sudo service nginx restart
