#!/usr/bin/env bash
# Install your load balancer
sudo apt update
sudo apt install -y haproxy

sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 52.73.245.246:80 check\n\tserver server2 54.146.73.137:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
