#!/usr/bin/env bash
# Is the host on the network

i=0

if [ "$#" -ne 1 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

for arg in "$@"; do
  [[ $i -ge 1 ]] && echo -e
  ping -c 5 "$arg"
  i+=1
done
