#!/usr/bin/env bash
# Process and PID file

PID_file="/var/run/myscript.pid"

sigterm_handler {
  echo "I hate the kill commande"
  rm -f "$PID_file"
  exit 0
}

sigint_handler {
  echo "Y U no love me?!"
}

sigquit_handler {
  rm -f "$PID_file"
  exit 0
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

echo "$$" > "$PID_file"

while true; do
  echo "To infinity and beyond"
  sleep 1
done
