#!/usr/bin/env bash
# displays "To infinity and beyond" indefinitely with a sleep 2 between iterations.

while true; do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
