#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

h=0
while [ $h -le 12 ]; do
  echo "Hour: $h"
  min=1
  while [ $min -lt 60 ]; do
    echo "$min"
    ((min++))
  done
  ((h++))
done
